---
title: "Figure 3"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
require(pacman)

```

Setup
```{r}
pacman::p_load("plyr", "tidyr", "lattice", "ggplot2", "dplyr", "patchwork", "afex", "emmeans", "multcomp",
              "cowplot","readr", "rmarkdown","Rmisc","devtools","gghalves","plotrix", "here")

abs_dic <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(abs_dic)

# width and height variables for saved plots
w = 5
h = 5

# nudge variables for rainclouds

nudge_dot_a = 1.15
nudge_dot_b = -1.15

nudge_cloud_a = 1.25
nudge_cloud_b = -1.25

# Make the figure folder if it doesn't exist yet
dir.create('../figures/', showWarnings = FALSE)

```

```{r}

# read the HRV data
data <- read.csv("hrv.txt")

# set some labels
data$Valence <- factor(data$Valence, levels = c("Low", "High"))
data$Valence <- revalue(data$Valence, c("Low"="Negative", "High"="Positive"))
data$Arousal <- factor(data$Arousal, levels = c("Low", "High"))



data$Arousal <- as.numeric(as.factor(data$Arousal))

# first we need to average over the learning times and then pivot the data to a 
# 'wider' format

data <- data %>%
  group_by(Valence, Arousal, Subject, Metric) %>%
  filter(Reject == 0) %>%
  summarise(Values = mean(Values)) %>%
  pivot_wider(names_from = c(Metric), values_from = Values)

data$xj <- jitter(as.numeric(as.factor(data$Arousal)), amount=0.05)
  
# now we can calculate a new matrix with mean and SE 
summary_data <- data %>%
  group_by(Valence, Arousal) %>%
  select(-Subject) %>%
  summarise_all(funs(mean, std.error))


```

Statistical analysis

```{r}

aov_1 <- aov_ez("Subject", "hf_peak", data_1, within = c("Valence", "Arousal"))

summary(aov_1)

```


Subpanel plots - hf_peak 
```{r HF Peak}

P_A <- ggplot(data = summary_data, aes(y = hf_peak_mean)) +
   geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = hf_peak_mean), position = position_nudge(0), alpha = 1) +
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = hf_peak),
                position = position_nudge(nudge_dot_a), alpha =.8, size=1.5)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = hf_peak),
                position = position_nudge(nudge_dot_b), alpha =.8,size=1.5) +
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = hf_peak_mean-hf_peak_std.error, ymax = hf_peak_mean+hf_peak_std.error),width = 0, size =1, position = position_nudge(0), alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence,y = hf_peak_mean),  alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence, y = hf_peak_mean), alpha = 1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal, color=Valence,fill = Valence,y = hf_peak), position = position_nudge(x = nudge_cloud_a), 
     side = "r", alpha = .6) +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal, color=Valence,fill = Valence,y = hf_peak), position = position_nudge(x = nudge_cloud_b), 
     side = "l", alpha = .6) +
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
     #Define additional settings
   xlab("Arousal") + ylab("HF Peak") +
   ggtitle('A') +
   theme_cowplot()+
   #theme(legend.position = "none") +
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c("#2C5AA0","#AA0000")) +
  scale_color_manual(values=c("#2C5AA0","#AA0000")) 
  
ggsave(filename=here("figures", "Figure4_A_hf_peak.svg"), plot=P_A, width = w, height = h,dpi=600)
ggsave(filename=here("figures", "Figure4_A_hf_peak.jpeg"), plot=P_A, width = w, height = h,dpi=600)

P_A
```

```{r LF Peak}

P_A <- ggplot(data = summary_data, aes(y = lf_peak_mean)) +
   geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = lf_peak_mean), position = position_nudge(0), alpha = 1) +
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = lf_peak),
                position = position_nudge(nudge_dot_a), alpha =.8, size=1.5)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = lf_peak),
                position = position_nudge(nudge_dot_b), alpha =.8,size=1.5) +
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = lf_peak_mean-lf_peak_std.error, ymax = lf_peak_mean+lf_peak_std.error),width = 0, size =1, position = position_nudge(0), alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence,y = lf_peak_mean),  alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence, y = lf_peak_mean), alpha = 1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal, color=Valence,fill = Valence,y = lf_peak), position = position_nudge(x = nudge_cloud_a), 
     side = "r", alpha = .6) +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal, color=Valence,fill = Valence,y = lf_peak), position = position_nudge(x = nudge_cloud_b), 
     side = "l", alpha = .6) +
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
     #Define additional settings
   xlab("Arousal") + ylab("LF Peak") +
   ggtitle('A') +
   theme_cowplot()+
   #theme(legend.position = "none") +
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c("#2C5AA0","#AA0000")) +
  scale_color_manual(values=c("#2C5AA0","#AA0000")) 
  
ggsave(filename=here("figures", "Figure4_A_lf_peak.svg"), plot=P_A, width = w, height = h,dpi=600)
ggsave(filename=here("figures", "Figure4_A_lf_peak.jpeg"), plot=P_A, width = w, height = h,dpi=600)

P_A
```

```{r HF Power}

P_A <- ggplot(data = summary_data, aes(y = hf_power_mean)) +
   geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = hf_power_mean), position = position_nudge(0), alpha = 1) +
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = hf_power),
                position = position_nudge(nudge_dot_a), alpha =.8, size=1.5)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = hf_power),
                position = position_nudge(nudge_dot_b), alpha =.8,size=1.5) +
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = hf_power_mean-hf_power_std.error, ymax = hf_power_mean+hf_power_std.error),width = 0, size =1, position = position_nudge(0), alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence,y = hf_power_mean),  alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence, y = hf_power_mean), alpha = 1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal, color=Valence,fill = Valence,y = hf_power), position = position_nudge(x = nudge_cloud_a), 
     side = "r", alpha = .6) +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal, color=Valence,fill = Valence,y = hf_power), position = position_nudge(x = nudge_cloud_b), 
     side = "l", alpha = .6) +
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
     #Define additional settings
   xlab("Arousal") + ylab("HF Power") +
   ggtitle('A') +
   theme_cowplot()+
   #theme(legend.position = "none") +
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c("#2C5AA0","#AA0000")) +
  scale_color_manual(values=c("#2C5AA0","#AA0000")) 
  
ggsave(filename=here("figures", "Figure4_A_hf_power.svg"), plot=P_A, width = w, height = h,dpi=600)
ggsave(filename=here("figures", "Figure4_A_hf_power.jpeg"), plot=P_A, width = w, height = h,dpi=600)

P_A

```


```{r LF Power}

P_A <- ggplot(data = summary_data, aes(y = lf_power_mean)) +
   geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = lf_power_mean), position = position_nudge(0), alpha = 1) +
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = lf_power),
                position = position_nudge(nudge_dot_a), alpha =.8, size=1.5)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = lf_power),
                position = position_nudge(nudge_dot_b), alpha =.8,size=1.5) +
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = lf_power_mean-lf_power_std.error, ymax = lf_power_mean+lf_power_std.error),width = 0, size =1, position = position_nudge(0), alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence,y = lf_power_mean),  alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence, y = lf_power_mean), alpha = 1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal, color=Valence,fill = Valence,y = lf_power), position = position_nudge(x = nudge_cloud_a), 
     side = "r", alpha = .6) +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal, color=Valence,fill = Valence,y = lf_power), position = position_nudge(x = nudge_cloud_b), 
     side = "l", alpha = .6) +
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
     #Define additional settings
   xlab("Arousal") + ylab("LF Power") +
   ggtitle('A') +
   theme_cowplot()+
   #theme(legend.position = "none") +
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c("#2C5AA0","#AA0000")) +
  scale_color_manual(values=c("#2C5AA0","#AA0000")) 
  
ggsave(filename=here("figures", "Figure4_A_lf_power.svg"), plot=P_A, width = w, height = h,dpi=600)
ggsave(filename=here("figures", "Figure4_A_lf_power.jpeg"), plot=P_A, width = w, height = h,dpi=600)

P_A

```

```{r mean BPM}

P_A <- ggplot(data = summary_data, aes(y = MeanBPM_mean)) +
   geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = MeanBPM_mean), position = position_nudge(0), alpha = 1) +
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = MeanBPM),
                position = position_nudge(nudge_dot_a), alpha =.8, size=1.5)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = MeanBPM),
                position = position_nudge(nudge_dot_b), alpha =.8,size=1.5) +
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = MeanBPM_mean-MeanBPM_std.error, ymax = MeanBPM_mean+MeanBPM_std.error),width = 0, size =1, position = position_nudge(0), alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence,y = MeanBPM_mean),  alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence, y = MeanBPM_mean), alpha = 1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal, color=Valence,fill = Valence,y = MeanBPM), position = position_nudge(x = nudge_cloud_a), 
     side = "r", alpha = .6) +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal, color=Valence,fill = Valence,y = MeanBPM), position = position_nudge(x = nudge_cloud_b), 
     side = "l", alpha = .6) +
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
     #Define additional settings
   xlab("Arousal") + ylab("Mean BPM") +
   ggtitle('A') +
   theme_cowplot()+
   #theme(legend.position = "none") +
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c("#2C5AA0","#AA0000")) +
  scale_color_manual(values=c("#2C5AA0","#AA0000")) 
  
ggsave(filename=here("figures", "Figure4_A_MeanBPM.svg"), plot=P_A, width = w, height = h,dpi=600)
ggsave(filename=here("figures", "Figure4_A_MeanBPM.jpeg"), plot=P_A, width = w, height = h,dpi=600)

P_A


aov_1 <- aov_ez("Subject", "MeanBPM", data, within = c("Valence", "Arousal"))

summary(aov_1)

```

```{r median BPM}

P_A <- ggplot(data = summary_data, aes(y = MedianBPM_mean)) +
   geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = MedianBPM_mean), position = position_nudge(0), alpha = 0.5, size = 2) +
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = MedianBPM),
                position = position_nudge(nudge_dot_a), alpha =.5, size=1.5)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = MedianBPM),
                position = position_nudge(nudge_dot_b), alpha =.5,size=1.5) +
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = MedianBPM_mean-MedianBPM_std.error, ymax = MedianBPM_mean+MedianBPM_std.error),width = 0, size =2, position = position_nudge(0), alpha = 0.5) +
   geom_line(aes(x = Arousal, color=Valence,y = MedianBPM_mean),  alpha = 0.5, size = 2) +
   geom_line(aes(x = Arousal, color=Valence, y = MedianBPM_mean), alpha = 0.5, size = 2) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal, color=Valence,fill = Valence,y = MedianBPM), position = position_nudge(x = nudge_cloud_a), 
     side = "r", alpha = .6) +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal, color=Valence,fill = Valence,y = MedianBPM), position = position_nudge(x = nudge_cloud_b), 
     side = "l", alpha = .6) +
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
     #Define additional settings
   xlab("Arousal") + ylab("MedianBPM") +
   ggtitle('A') +
   theme_cowplot()+
   #theme(legend.position = "none") +
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c("#2C5AA0","#AA0000")) +
  scale_color_manual(values=c("#2C5AA0","#AA0000")) 
  
ggsave(filename=here("figures", "Figure4_A_MedianBPM.svg"), plot=P_A, width = w, height = h,dpi=600)
ggsave(filename=here("figures", "Figure4_A_MedianBPM.jpeg"), plot=P_A, width = w, height = h,dpi=600)

P_A

## stats

# fit 2x2 repeated measures ANOVA
aov_1 <- aov_ez("Subject", "MedianBPM", data, within = c("Valence", "Arousal"))


# fit estimated marginal means and perform post-hoc contrasts
m1 <- emmeans(aov_1$aov, "Valence", by = "Arousal")
m2 <- emmeans(aov_1$aov, "Arousal", by = "Valence")
m3 <- emmeans(aov_1$aov, ~Valence*Arousal)

summary(pairs(m1))
summary(pairs(m2))
summary(pairs(m3))

#summary(aov_2)

```


```{r RMSSD}

P_A <- ggplot(data = summary_data, aes(y = RMSSD_mean)) +
   geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = RMSSD_mean), position = position_nudge(0), alpha = 1) +
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = RMSSD),
                position = position_nudge(nudge_dot_a), alpha =.8, size=1.5)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = RMSSD),
                position = position_nudge(nudge_dot_b), alpha =.8,size=1.5) +
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = RMSSD_mean-RMSSD_std.error, ymax = RMSSD_mean+RMSSD_std.error),width = 0, size =1, position = position_nudge(0), alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence,y = RMSSD_mean),  alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence, y = RMSSD_mean), alpha = 1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal, color=Valence,fill = Valence,y = RMSSD), position = position_nudge(x = nudge_cloud_a), 
     side = "r", alpha = .6) +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal, color=Valence,fill = Valence,y = RMSSD), position = position_nudge(x = nudge_cloud_b), 
     side = "l", alpha = .6) +
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
     #Define additional settings
   xlab("Arousal") + ylab("RMSSD") +
   ggtitle('A') +
   theme_cowplot()+
   #theme(legend.position = "none") +
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c("#2C5AA0","#AA0000")) +
  scale_color_manual(values=c("#2C5AA0","#AA0000")) 
  
ggsave(filename=here("figures", "Figure4_A_RMSSD.svg"), plot=P_A, width = w, height = h,dpi=600)
ggsave(filename=here("figures", "Figure4_A_RMSSD.jpeg"), plot=P_A, width = w, height = h,dpi=600)

P_A


aov_1 <- aov_ez("Subject", "RMSSD", data, within = c("Valence", "Arousal"))

summary(aov_1)

```

```{r pnn50}

P_A <- ggplot(data = summary_data, aes(y = pnn50_mean)) +
   geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = pnn50_mean), position = position_nudge(0), alpha = 1) +
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = pnn50),
                position = position_nudge(nudge_dot_a), alpha =.8, size=1.5)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = pnn50),
                position = position_nudge(nudge_dot_b), alpha =.8,size=1.5) +
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = pnn50_mean-pnn50_std.error, ymax = pnn50_mean+pnn50_std.error),width = 0, size =1, position = position_nudge(0), alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence,y = pnn50_mean),  alpha = 1) +
   geom_line(aes(x = Arousal, color=Valence, y = pnn50_mean), alpha = 1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal, color=Valence,fill = Valence,y = pnn50), position = position_nudge(x = nudge_cloud_a), 
     side = "r", alpha = .6) +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal, color=Valence,fill = Valence,y = pnn50), position = position_nudge(x = nudge_cloud_b), 
     side = "l", alpha = .6) +
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
     #Define additional settings
   xlab("Arousal") + ylab("pnn50") +
   ggtitle('A') +
   theme_cowplot()+
   #theme(legend.position = "none") +
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c("#2C5AA0","#AA0000")) +
  scale_color_manual(values=c("#2C5AA0","#AA0000")) 
  
ggsave(filename=here("figures", "Figure4_A_pnn50.svg"), plot=P_A, width = w, height = h,dpi=600)
ggsave(filename=here("figures", "Figure4_A_pnn50.jpeg"), plot=P_A, width = w, height = h,dpi=600)

P_A


aov_1 <- aov_ez("Subject", "pnn50", data, within = c("Valence", "Arousal"))

summary(aov_1)

Within_Fitted_StudyMethod<-emmeans(aov_1, ~Valence)

```


Assemble plots into overall figure. 
```{r}

mp<- P_A + P_B + P_C + P_D + P_E + P_F + plot_layout(guides = 'collect', ncol = 3)#, heights = c(10,10), widths = c(10,10,10))


ggsave(filename="figures/Figure3_ALL.svg", plot=mp, width = 12, height = 6,dpi=600)

ggsave(filename="figures/Figure3_ALL.jpeg", plot=mp, width = 12, height = 6,dpi=600)

ggsave(filename="figures/Figure3_lowres.jpeg", plot=mp, width = 12, height = 6,dpi=300)

mp

```


